### ISSUE TITLE
catlog unvisible for CM

### ISSUE THREAD

**Issue by Superwallah** [nolanlawson/ChordReaderRoot#11]
I am (still) running an (unsupported) Cyanogenmod on my phone (GT-i9505).
Since beginning of this year, catlog is not displayed by the Google Play search anymore for my device. What was changed? Why can't I use Catlog anymore?

**Comment by nolanlawson** [comment]
The CatLog repo is over in https://github.com/nolanlawson/catlog but I am not maintaining CatLog anymore. Please try MatLog instead: https://play.google.com/store/apps/details?id=com.pluscubed.matlog
